spring.datasource.url=mysql://bab65dd9f62bab:32b2142b@us-cdbr-iron-east-03.cleardb.net/heroku_1e7bda458a18dcd
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true