spring.profiles.active=dev

spring.jpa.properties.hibernate.jdbc.time_zone = UTC

jwt.secret=segredodosdeuses
jwt.expiration=600000

spring.mail.host=smtp.gmail.com
spring.mail.username=4betpt@gmail.com
spring.mail.password=dwlpsolvjwxsfzyb
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=src/main/resources/keystore.p12
#server.ssl.key-store-password=segredodosdeuses